### ISSUE TITLE
Script configuration documentation

### ISSUE THREAD

**Issue by webalexeu** [mch1307/jeedom-nhc#2]
Hello,

In the wiki documentation, I didnt't find how to configure "switch": action script (http) 

The picture is not respresenting this and I don't find documentation on URL structure
I guess it should be something like http://host:8081/index.php?arg1=...

Thank you for your help,
Alexandre

**Comment by abbar21** [comment]
Hello,

I've the same issue... 
Thanks for your work !

**Comment by mch1307** [comment]
Hi,
I have updated the wiki page, hope it's clearer now.
The script should be: http://host:port/jeedom?id=XX&value=#slider#  where XX is the jeedom ID of the device

**Comment by mch1307** [comment]
The doc was not correct. In fact you need an "on" and "off" scripts, not a switch.
Let me know if it's ok for you now

**Comment by abbar21** [comment]
Hi,

Thanks for your answer !
I think I’ll do not have the time before my WE to test. 
I have an error message in the log to but maybe it’s a wrong IP in the conf file. But it see my NHC config.
Great job !!!

Best regards

**Comment by abbar21** [comment]
Hello,

I've this error in the error log file, but I cannot see the syntax error in the code. Had you already the issue ?
Maybe a "bad character" in the name of my "NHC actions » ?
thanks a lot
undefined:1
{"cmd":"listactions","data":[ {"id":0,"name":"action_porte_entrée","type":1,"location":4,"value1":100},{"id":1,"name":"Vestiaire","type":1,"location":4,"value1":0},{"id":2,"name":"Wc Bas","type":1,"location":4,"value1":0},{"id":3,"name":"Led Escalier","type":1,"location":4,"value1":0},{"id":4,"name":"Colonnes Cuisine","type":1,"location":5,"value1":100},{"id":5,"name":"Extérieur annexe","type":1,"location":1,"value1":0},{"id":6,"name":"Tableaux SàM","type":1,"location":5,"value1":0},{"id":7,"name":"Bureau","type":1,"location":7,"value1":0},{"id":8,"name":"Mirroir SdB","type":1,"location":8,"value1":0},{"id":9,"name":"SdB","type":1,"location":8,"value1":0},{"id":10,"name":"Wc Haut","type":1,"location":8,"value1":0},{"id":11,"name":"Cage escaliers","type":1,"location":6,"value1":0},{"id":12,"name":"Entrée de garage","type":1,"location":2,"value1":0},{"id":18,"name":"Meuble Tv","type":1,"location":3,"value1":0},{"id":20,"name":"Meuble Salon Feux","type":1,"location":3,"value1":0},{"id":32,"name

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.routeNhc (/opt/jeedom-nhc/lib/router.js:10:20)
    at Socket.<anonymous> (/opt/jeedom-nhc/lib/nhc.js:61:12)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:249:13)
    at Socket.Readable.push (_stream_readable.js:211:10)
    at TCP.onread (net.js:585:20)

**Comment by mch1307** [comment]
Hi,
I would say this is probably due to the fact the the listactions result is long and not sent in one packet.. would say it's a bug in my code :(
I have created issue #3 for this

**Comment by mch1307** [comment]
Documentation updated
