### ISSUE TITLE
Config problem in Jeedom 

### ISSUE THREAD

**Issue by abbar21** [mch1307/jeedom-nhc#4]
No luck, it's not working but maybe you'll see the mistake.
<img width="238" alt="capture d ecran 2017-08-18 a 18 21 03" src="https://user-images.githubusercontent.com/31033427/29468066-0fc76c16-8443-11e7-875e-a987e88d342f.png">
<img width="1475" alt="capture d ecran 2017-08-18 a 18 20 38" src="https://user-images.githubusercontent.com/31033427/29468068-0fe8b1b4-8443-11e7-802c-e5916895875d.png">
<img width="923" alt="capture d ecran 2017-08-18 a 18 20 31" src="https://user-images.githubusercontent.com/31033427/29468067-0fe81e7a-8443-11e7-8043-8728e95eaec1.png">
<img width="1633" alt="capture d ecran 2017-08-18 a 18 20 14" src="https://user-images.githubusercontent.com/31033427/29468069-0fea53d4-8443-11e7-89ca-42e71dc3f046.png">

**Comment by mch1307** [comment]
The script part looks fine.
The next thing to check how the process will match the equipment defined in Jeedom with the one defined in Niko. This is done by matching the Niko location to the Jeedom object and then the Niko action name to the Jeedom equipment. In your case, looks ok too.
For some reason, the process is not able to link Jeedom to NHC, so I will need the full jeedom-nhc logs (in debug mode), you can upload them as txt, better than pdf ;)
I suspect the process doesn't get the info from Jeedom, but we will check that with the logs

**Comment by abbar21** [comment]
Maybe .docx is better ?
In my case, "salon feux," is nhc Id 33 
[Niko NHC log.docx](https://github.com/mch1307/jeedom-nhc/files/1235720/Niko.NHC.log.docx)

**Comment by abbar21** [comment]
Just a suggestion, do I need to change something in the Jeedom API settings ?
<img width="1614" alt="capture d ecran 2017-08-18 a 23 45 07" src="https://user-images.githubusercontent.com/31033427/29478940-e21c57b8-846f-11e7-8fc6-4a7865231fa9.png">

**Comment by mch1307** [comment]
Yes, might be.. I have to check.
There is a place in jeedom UI where you can see track of API access. You
can have a look there. I will check later on my side

**Comment by abbar21** [comment]
Jeedom API Log

[2017-08-19 00:17:34][INFO] : {"jsonrpc":"2.0","method":"eqLogic::byType","id":"0","params":{"apikey":"XxerlUdCcB29jZTAnk0aVC0MDqTL9mP2","type":"script"}} - IP :192.168.1.105
[2017-08-19 00:17:34][INFO] : {"jsonrpc":"2.0","method":"object::all","id":"0","params":{"apikey":"XxerlUdCcB29jZTAnk0aVC0MDqTL9mP2"}} - IP :192.168.1.105
[2017-08-19 00:17:34][INFO] : {"jsonrpc":"2.0","method":"cmd::byEqLogicId","id":"0","params":{"apikey":"XxerlUdCcB29jZTAnk0aVC0MDqTL9mP2","eqLogic_id":"1"}} - IP :192.168.1.105
[2017-08-19 00:17:40][DEBUG] : Exécution de : [Salons][salon feux,][updState]

**Comment by mch1307** [comment]
On my side I have:
![image](https://user-images.githubusercontent.com/17752394/29483947-5a68d1b2-84b4-11e7-9a53-db3cc7840ec3.png)
and
![image](https://user-images.githubusercontent.com/17752394/29483953-6cbbb7da-84b4-11e7-8de9-600ca1f570ef.png)

**Comment by abbar21** [comment]
In IE nothing was selected. But in safari, I have same as you. Do you see something in the jeedom-nhc.log or in the Jeedom API log ?

**Comment by mch1307** [comment]
Can you try to type this url in a web browser and see if the state is updated in Jeedom?
http://192.168.1.105/core/api/jeeApi.php?apikey=XxerlUdCcB29jZTAnk0aVC0MDqTL9mP2&type=cmd&id=5&slider=0
http://192.168.1.105/core/api/jeeApi.php?apikey=XxerlUdCcB29jZTAnk0aVC0MDqTL9mP2&type=cmd&id=5&slider=100

**Comment by abbar21** [comment]
Yes it works, the slider is updated

**Comment by mch1307** [comment]
So the way NHC -> Jeedom works fine. If you switch a light in Niko, it gets updated in Jeedom right?
And if you switch the same light from Jeedom, does it get really switched?

**Comment by abbar21** [comment]
Yes NHC -> Jeedom works fine. When the light is switched on/off it's updated after 1sec in Jeedom. But Jeedom -> NHC doesn't work... I don't know if it's important but this light is on NHC dimmable module.

**Comment by abbar21** [comment]
For info, when I use Tcpdump on the raspberry, nothing's happen when I change the slider position in Jeedom

pi@raspberrypi:~ $ sudo tcpdump -i eth0 -vv dst 192.168.1.60
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
09:33:36.024391 IP (tos 0x0, ttl 64, id 35152, offset 0, flags [DF], proto TCP (6), length 40)
    Jeedom.49278 > Niko.8000: Flags [.], cksum 0x8410 (incorrect -> 0x24c4), seq 2681515642, ack 3084103464, win 29200, length 0
09:33:41.064360 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has Niko tell Jeedom, length 28
^C
2 packets captured
3 packets received by filter
0 packets dropped by kernel
pi@raspberrypi:~ $

**Comment by mch1307** [comment]
Can you tail the jeedom-nhc log (tail -f /opt/jeedom-nhc/log/*.log) and then try to switch the light from jeedom? Send me the ouptut of the tail command

**Comment by abbar21** [comment]
Nothing happens when I switch the light from jeedom...

[Niko NHC Tail log.docx](https://github.com/mch1307/jeedom-nhc/files/1237326/Niko.NHC.Tail.log.docx)

**Comment by abbar21** [comment]
When I send this URL in the browser : http://192.168.1.105:80/jeedom?id=1&value=#slider# I have this error : The requested URL /jeedom was not found on this server. Is it "normal" ?

**Comment by mch1307** [comment]
Jeedom-nhc listens on port 8081 by default, did you change this in the conf.js file? If not, try  http://192.168.1.105:8081/jeedom?id=1&value=100 in your browser.

**Comment by abbar21** [comment]
I have not changed the .conf file
But this URL work fine http://192.168.1.105:8081/jeedom?id=1&value=100 !!! Which line do I need to change in the cons.js ?


pi@raspberrypi:/ $ cat /opt/jeedom-nhc/conf/conf.js 
var path = require('path')
var cfg = {}

cfg.JEEDOM = {}
cfg.NHC = {}
cfg.DAEMON = {}

cfg.DAEMON.logFile = path.join(__dirname, '../log/jeedom-nhc.log')
cfg.DAEMON.logLevel = process.env.LOGLEVEL || 'INFO'
cfg.DAEMON.listen = process.env.LISTEN || 8081

cfg.JEEDOM.host = process.env.JEEHOST
cfg.JEEDOM.port = process.env.JEEPORT || 80
cfg.JEEDOM.urlRoot = process.env.JEEURL
cfg.JEEDOM.apiPath = '/core/api/jeeApi.php?'
cfg.JEEDOM.apiUrl = cfg.JEEDOM.urlRoot + cfg.JEEDOM.apiPath
cfg.JEEDOM.apiKey = process.env.JEEAPI

cfg.NHC.host = process.env.NHCHOST
cfg.NHC.port = process.env.NHCPORT || 8000
cfg.NHC.keepAlive = process.env.NHCKEEPALIVE || 60000
cfg.NHC.registerMsg = '{"cmd":"startevents"}'
cfg.NHC.equMsg = '{"cmd":"listactions"}'
cfg.NHC.locMsg = '{"cmd":"listlocations"}'

cfg.URLQRY = {
  apikey: cfg.JEEDOM.apiKey,
  type: undefined,
  id: undefined
}
module.exports = cfg

**Comment by mch1307** [comment]
You don't need to change any config, just change the URL you have setup in Jeedom (change the port from 80 to 8081)

**Comment by abbar21** [comment]
YESSSS ! It's working !
Maybe could you change the URL in the wiki !
This week I'll config my all NHC in Jeedom

**Comment by mch1307** [comment]
Good news!
The url in the wiki states host:port which seems ok. I will add a warning that by default it is on 8081 ;)

**Comment by abbar21** [comment]
For info the name of "location" on NHC with "&" exemple "cuisine & salle à manger" is not supported in Jeedom. Second warning ? ;)

**Comment by mch1307** [comment]
Good point ;)

**Comment by abbar21** [comment]
I have a question. Again...
Wich configuration have you for not dimmable lamp. Just on/off with a change of the icon in jeedom. I have a ON button and a Off button but no return of the state with an icon. Thx

**Comment by mch1307** [comment]
As usual, etat, on, off and updState
The on and off should be of type "Action" and "Défault" instead of "Curseur"
The HTTP script should be as follows: http://host:port/jeedom?id=x&value=y where y is 0 for off and 100 for on
![image](https://user-images.githubusercontent.com/17752394/29754008-5741779e-8b7d-11e7-9757-944f2a96d512.png)

**Comment by abbar21** [comment]
Do you have a bulb icon who change his state when the light is ON or Off ?
